import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

/**
 * The site is retired. Every request — pages, API routes, and the static
 * artifacts under /public (worksheets, PDFs, images) — serves the holding
 * page at /unavailable.
 *
 * To bring the site back: delete this file and revert app/layout.tsx.
 * The rest of the application is untouched.
 */
export function middleware(request: NextRequest) {
  const url = request.nextUrl.clone()
  url.pathname = '/unavailable'
  url.search = ''

  const response = NextResponse.rewrite(url)
  response.headers.set('X-Robots-Tag', 'noindex, nofollow')
  return response
}

export const config = {
  matcher: [
    /*
     * Match everything except what the holding page itself needs to render:
     *   _next/static, _next/image  build output
     *   favicon.ico, icon.svg      tab icon
     *   og-image.png               social card for already-shared links
     *   robots.txt, sitemap.xml    generated by app/robots.ts + app/sitemap.ts,
     *                              and must stay reachable to signal noindex
     *   unavailable                the holding page (rewriting it to itself loops)
     */
    '/((?!_next/static|_next/image|favicon.ico|icon.svg|og-image.png|robots.txt|sitemap.xml|unavailable).*)',
  ],
}
